# Package Overview
package_name: bikeshare_model

# Data Files
training_data_file: bike-sharing-dataset.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (Count)
target: cnt

pipeline_name: bikeshare_model
pipeline_save_file: bikeshare__model_output_v



features:      # final features to be use
  - dteday
  - season
  - hr
  - holiday
  - weekday
  - workingday
  - weathersit
  - temp
  - atemp
  - hum
  - windspeed
  - casual
  - registered
  - yr
  - mnth

# Features inside processing pipeline

unused_fields:  # Features to drop Specific fields in the processing pipeline
 - dteday
 - casual
 - registered
 - weekday

numerical_features:
 - temp
 - atemp
 - hum
 - windspeed


  
# set train/test split
test_size: 0.20

# to set the random seed
random_state: 42
# alogrithm parameters
n_estimators: 100
max_depth: 10


